# Generated by Django 5.0.3 on 2025-03-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_remove_loan_loan_id_remove_loan_monthly_installment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='status',
        ),
        migrations.AddField(
            model_name='loan',
            name='is_foreclosed',
            field=models.BooleanField(default=False),
        ),
    ]
