# Generated by Django 5.0.3 on 2025-03-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_remove_loan_status_loan_is_foreclosed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='is_foreclosed',
        ),
        migrations.AddField(
            model_name='loan',
            name='collateral',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
