# Generated by Django 5.0.3 on 2025-03-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loan_loan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='monthly_installment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
